// Red Flag agent → Solar Sentinel integration layer.
//
// Usage (Kiran):
//   import { toSentinel } from "@/lib/agent";
//   const detail = toSentinel(agentReportJson, { id: "parcel-a", latitude: 35.9056, longitude: -114.9345, capacityMW: 180 });
//   // detail is a complete ProjectDetail — swap directly for mockData entries.
//
// Fixtures to develop against live in agent_backend/sentinel-samples/*.sentinel.json
// (already in ProjectDetail shape; generated by the Python twin adapter and
// parity-tested against this one).

export { toSentinel, band } from "./adapter";
export type { SentinelMeta } from "./adapter";
export type {
  AgentReport,
  AgentRedFlag,
  AgentContradiction,
  AgentDimensionScore,
  AgentActionPack,
  AgentAgencyAction,
  AgentAcquiredData,
  Severity,
  RAG,
} from "./report";
